#{% set version = "7.1.0" %}
#{% set quality = "final" %}
{% set version = "7.1.1" %}
{% set quality = "beta" %}

package:
  name: pyferret
  version: {{ version }}

source:
  fn: pyferret-{{ version }}.tar.gz
  url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}-{{ quality }}.tar.gz
  #sha256: a3c2823068d2b20d69233f7d93653ecf10ff006e4663a8d3a8441db644cbe4c6
  patches:
    - site_specific.patch  # [not win]
    - linux-platform_specific.patch  # [linux]
    - osx-platform_specific.patch  # [osx]

build:
  number: 1
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - gcc  # [not win]
  run:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - pyqt 5.6.*  # [not osx]
    - pyqt 4.11.*  # [osx]
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pyferret
  commands:
    - conda inspect linkages -p $PREFIX pyferret  # [not win]
    - conda inspect objects -p $PREFIX pyferret  # [osx]

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
